In [7]:
import numpy as np

# Create sample matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C_add = A + B
print(C_add)
C_sub = A - B
print(C_sub)
C_mul = A * B
print(C_mul)
C_dot = np.dot(A, B)
print(C_dot)
A_transpose = np.transpose(A)
print(A_transpose)
try:
    A_inv = np.linalg.inv(A)
except np.linalg.LinAlgError:
    A_inv = None
print(A_inv)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[1 3]
 [2 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [8]:
"""Printing image as array"""
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
b_path = r"C:\Users\BhavyeBhasin\Downloads\wolfss.png" 
img = mpimg.imread(b_path)
print(img)

[[[0.8        0.7882353  0.76862746 1.        ]
  [0.81960785 0.80784315 0.7882353  1.        ]
  [0.83137256 0.81960785 0.8        1.        ]
  ...
  [0.70980394 0.6745098  0.654902   1.        ]
  [0.7372549  0.70980394 0.6862745  1.        ]
  [0.7647059  0.7411765  0.72156864 1.        ]]

 [[0.8235294  0.8039216  0.7882353  1.        ]
  [0.8352941  0.81960785 0.8        1.        ]
  [0.84705883 0.83137256 0.8117647  1.        ]
  ...
  [0.72156864 0.6901961  0.67058825 1.        ]
  [0.7372549  0.70980394 0.6862745  1.        ]
  [0.7647059  0.7411765  0.72156864 1.        ]]

 [[0.84313726 0.81960785 0.8039216  1.        ]
  [0.8509804  0.83137256 0.8156863  1.        ]
  [0.8627451  0.8392157  0.8235294  1.        ]
  ...
  [0.7647059  0.7372549  0.7176471  1.        ]
  [0.7607843  0.7411765  0.7137255  1.        ]
  [0.78039217 0.7607843  0.7372549  1.        ]]

 ...

 [[0.5882353  0.4627451  0.3137255  1.        ]
  [0.58431375 0.45882353 0.3137255  1.        ]
  [0.58823